### ISSUE TITLE
Floor plan generation responsiveness

### ISSUE THREAD

**Issue by aarongerber** [ranjian0/building_tools#104]
First off, great plugin. If you have a place to donate love to know. Can't afford much since this is a hobby but wouldn't mind buying you a drink. :)

It seems there is room for improvement when first generating a floor plan (in the least a straight rectangle floor plan). It's basically a plane, but take around 5-10 seconds sometimes to update as you change size. Other updates to the design of the buildings are way faster.  Thanks for considering this improvement.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Blender Version 2.83
 - Addon Version 1.0-beta

**Comment by aarongerber** [comment]
I aim this at more of a bug since a brand new project seems to do it rather fast but once you have 20 some buildings it can chuck along sometimes.

**Comment by ranjian0** [comment]
Hi and thanks for offering to donate, I am in the process of setting up a Patreon account. Should be ready soon.

As for the issue, building tools works like most other tools in blender, this should not be happening.

Does this only happen for floorplans?

**Comment by aarongerber** [comment]
This only is happening with the floor plan creation. I don't see this sort of delay while creating the buildings in edit mode. I expect this plugin (as a new user to Blender) to behave a lot like the plane mesh object and it usually does with one building. I'll see if I can get a setup to share with you that demonstrates this.

**Comment by ranjian0** [comment]
I am not able to duplicate this. Perhaps you can provide a blend file

**Comment by ranjian0** [comment]
Adding a new floorplan to fresh blend file causes a 1s lag. Consecutive additions are instantaneous. 

Did some profiling, addon code to create floorplan runs in about 0.001s. Not sure what is causing the lag.
