### ISSUE TITLE
Using OSM floorplans with the add-on?

### ISSUE THREAD

**Issue by LadyRover** [ranjian0/building_tools#109]
Hey,

cool add-on, well done!
I got a little feature suggestion.

Architects and Arch Viz usually work with existing cities.
Very often the 3D geometry is not available, but there are ways around it.

On one side there is the Open Street Map (OSM) add-on which lets you import buildings and more.
A lot of this geometry is incomplete though, has missing roofs and similar. The heights are not reliable either. So its helpful, but not the 3d content is not really usable.
Than there is Google Earth, there are ways to extract its 3D geometry reasonably well, it works to be used as a fairly accurate 3D reference, but apart from that its quality works only for a backdrop.

So, I do import Google geometry as reference, than import the 2D floorplans of the building via OSM. Next step I extrude the buildings so that the building heights match the heights of the Google 3D reference geometry.
Once that it done I model the roof by hand.

Now here is the feature request:
Could you make it possible that the floorplan meshes imported from open street map become floorplans for your add-on?
It would save tons of time when one could do the detailing of the buildings, and especially the roofs with your add-on.

Keep up the good work, your add-on looks already very nice.

Very best regards,

Franziska

**Comment by ranjian0** [comment]
Will keep this at the back of my mind.

**Comment by LadyRover** [comment]
Great!
Am 5. Juni 2020 08:41:24 schrieb Ian Karanja <notifications@github.com>:

**Comment by ranjian0** [comment]
Closed as out of scope.
