### ISSUE TITLE
Can't create window on perfectly valid face

### ISSUE THREAD

**Issue by MCrafterzz** [ranjian0/building_tools#134]
For some reason it thinks the following situation is not a valid n-gon:
![image](https://user-images.githubusercontent.com/19669673/85265207-35cb2a80-b472-11ea-99f1-292ab6af289b.png)
So you can't add windows, doors etc

It's the default square floorplan with 3 added floors without slabs. Trying to add a window to all three floors at the same time crashes blender, probably due to it not being a valid n-gon.

**Comment by luckykadam** [comment]
A valid n-gon is defined as:
https://github.com/ranjian0/building_tool/blob/626fbd14e1fbf194d84d805fa3ea172ca2c378fe/utils/util_mesh.py#L96

Adding floors without slabs is not recommended, because it will almost always cause this issue.

**Comment by MCrafterzz** [comment]
> A valid n-gon is defined as:
> https://github.com/ranjian0/building_tool/blob/626fbd14e1fbf194d84d805fa3ea172ca2c378fe/utils/util_mesh.py#L96
> 
> Adding floors without slabs is not recommended, because it will almost always cause this issue.

Most buildings irl don't have slabs

**Comment by ranjian0** [comment]
@MCrafterzz an n-gon in building tools is any rectangular face with more than 4 vertices.

The face shown is rectangular, but the horizontal edges contain many subdivisions.

> Most buildings irl don't have slabs

This issue is not easy to solve when there are slabs. When no slabs are present, it becomes a nightmare. 
Since building tools uses blender's edit mode tools, surrounding geometry affects the operations that are possible. Currently, it is not possible to make a `clean` inset for n-gon that allows consequtive operations to create predictable geometry.

**Comment by MCrafterzz** [comment]
> @MCrafterzz an n-gon in building tools is any rectangular face with more than 4 vertices.
> 
> The face shown is rectangular, but the horizontal edges contain many subdivisions.
> 
> > Most buildings irl don't have slabs
> 
> This issue is not easy to solve when there are slabs. When no slabs are present, it becomes a nightmare.
> Since building tools uses blender's edit mode tools, surrounding geometry affects the operations that are possible. Currently, it is not possible to make a `clean` inset for n-gon that allows consequtive operations to create predictable geometry.

If that face didn't contain the vertex then it would work flawlessly. So why connect that vertex to a face that doesn't need it? The visual result is the same.

**Comment by ranjian0** [comment]
The geometry is connected as a consequence of say `making a loop cut`. If down the line I want to make another loop cut, it will not be possible if the initial geometry was not correct.

Determining how to solve this means you need to know how the geometry is now, and how it will be when you have already done everything.

**Comment by alic44** [comment]
In summary, if you want to be able to add windows or doors to both the first and second floor (or any adjacent floors) of a building, you should use slabs. Otherwise your second floor won't have windows or your first floor won't have a door (or windows).

**Comment by ranjian0** [comment]
Did a bit of hacking and fixed this.
Solved by 3fe085ea664405ae8a7cf0b050a9fcf7cee11384
Fingers Crossed!
