### ISSUE TITLE
Allow non-straight faces for windows etc

### ISSUE THREAD

**Issue by MCrafterzz** [ranjian0/building_tools#136]
Defiently not high priority by and means and I don't know how hard it would be to implement but some buildings (skyscrapers) become narrower and narrower the further up they go. Create a window for such a square would be defiantly work visually, instead of having the window 90* compared to the ground it would be rotated according to the selected face. This would allow for the creating of a whole bunch of interesting buildings!

Note: This does not in anyway mean that the tool would add a way to create such floors, the floors would be created manually.

**Comment by ranjian0** [comment]
@luckykadam wrote some code that can help with this. Will look into it for windows only. Doesn't make sense for other things like doors and balconies.

**Comment by MCrafterzz** [comment]
Only windows would make sence
