### ISSUE TITLE
Easy Construction Of Release Archives, Redux

### ISSUE THREAD

**Issue by ldo** [ranjian0/building_tools#137]
You’re probably going to hate me for this, but following on from #99, I have had a better idea.

I have generalized the `make-dist` script I submitted in the above issue into a new `make-snapshot` script, included in my [`git-useful`](https://github.com/ldo/git-useful) repo. This script can read a file in `MANIFEST.in` format, which is documented [here](https://packaging.python.org/guides/using-manifest-in/). This consists of a sequence of various forms of include/exclude directives that can contain wildcards. Maintaining such a file would be easier than maintaining an entire script. For example, here is a suitable manifest file for the `building_tool` project:

```
    include LICENSE README.md TODO
    include __init__.py
    recursive-include core *
    recursive-include docs *
    recursive-include utils *
```

Much simpler, don’t you think?

Also, I have added the option for the manifest itself to come from the commit history.

**Comment by ranjian0** [comment]
The script seems to have buffed up quite a bit from the previous `make_dist.py`. I will test it out sometime this week as I also figure out how to add comprehensive tests to the addon. I am sure it will come in handy as addon continues to grow in size. Thanks for making this and sharing here. I had no idea what to do about issue #93 and other similar problems with GitHub releases before this.

Cheers

**Comment by ldo** [comment]
I just tried downloading and installing your 1.0.0 release archive, and that worked fine.

Maybe there was some issue with the top-level directory name within the archive, containing hyphens or dots or something? My `make-snapshot` script always uses the base archive file name for this, without the version, e.g.

```
make-snapshot building_tool v1.0 ...
```

will create a file called `building_tool-v1.0.zip`, but within that archive you will see that the top-level directory name is just `building_tool`, and that is the name of the directory that Blender will create when installing it.. This should avoid problems.

**Comment by ranjian0** [comment]
@ldo I have recently updated repo structure in preparation of adding unit tests for the addon. With the new structure, the 'make-dist' script seems to not be working i.e generated zip file is empty. This is true also for your suggested 'make-snapshot' script. Any insight you could offer is highly appreciated.

The issue seems to be `git` related. I am assuming that my old git tags are based on the old repo structure and that I would need new tags with new structure for the script to work. Am I warm!!

**Comment by ldo** [comment]
Seems to work OK. I just updated my local copy of your repo, and tried the command

```
make-snapshot -m MANIFEST.in building_tool v1.0.0
```

with the abovementioned contents for `MANIFEST.in`, and it created a file `building_tool-v1.0.0.zip` with the contents you would expect:

```
	ldo@theon:building_tool> lsar -l building_tool-v1.0.0.zip 
	building_tool-v1.0.0.zip: Zip
		 Flags  File size   Ratio  Mode  Date       Time   Name
		 =====  ==========  =====  ====  ========== =====  ====
	  0. -----        1068  41.2%  Defl  2019-04-27 14:09  building_tool/LICENSE
	  1. -----        1716  47.4%  Defl  2020-06-10 19:23  building_tool/README.md
	  2. -----        2328  46.6%  Defl  2020-06-10 18:35  building_tool/TODO
	  3. -----        3523  68.8%  Defl  2020-06-09 18:13  building_tool/__init__.py
	  4. -----          53  30.2%  Defl  2018-05-26 17:36  building_tool/core/__init__.py
	  5. -----        2478  65.2%  Defl  2020-06-09 18:13  building_tool/core/arch.py
	  6. -----         334  56.3%  Defl  2020-03-11 17:44  building_tool/core/balcony/__init__.py
	...
	 62. -----        3031  67.5%  Defl  2019-08-18 20:19  building_tool/utils/util_geometry.py
	 63. -----        4006  67.0%  Defl  2020-06-09 18:13  building_tool/utils/util_material.py
	 64. -----       10738  72.0%  Defl  2020-06-11 08:14  building_tool/utils/util_mesh.py
	 65. -----         891  59.4%  Defl  2019-07-20 19:35  building_tool/utils/util_object.py
	 66. -----       27468  78.5%  Defl  2020-05-29 20:33  building_tool/utils/util_skeleton.py
	(Flags: D=Directory, R=Resource fork, L=Link, E=Encrypted, @=Extended attributes)
	(Mode: Defl=Deflate)
```

Do you get any errors from running my script? Because it has a check to prevent the creation of empty archives.

**Comment by ldo** [comment]
Yes, you are right. I checked the `make-dist.py` script as committed in your repo, and it creates an empty archive. I extracted my original `make-dist` script and tried running that, and it throws an error because the `core/` subdirectory no longer exists.

**Comment by ranjian0** [comment]
With a tag added, it all works.
