### ISSUE TITLE
Blender crashes when width or length is larger than 10 meter!

### ISSUE THREAD

**Issue by Qomolangma888** [ranjian0/building_tools#140]
In floor plan settings, the width or length is larger than 10 meter, then enter edit-mode, if you add window on selected face, Blender will crash. I test it many times! So, I hope authors can fix the bug as soon as possible, Thanks!
At the same time, I wish authors can improve large number windows generating speed, meanwhile, I sometimes will create very large scale plant, for example length larger then 1000[m], I hope author can large width and length limits!

**Comment by MCrafterzz** [comment]
Does it only happen when rhe width or height is above 10m?

**Comment by Qomolangma888** [comment]
At first, I set width = 100(100 is the largest value), blender crashed; then I set width=50, Blender alse crashed, then I set width = 10, Blender can run, I use Blender 2.9 Alpha everyday built version, meanwhile I know there are many bugs in current Blender 2.9. I will test it continuously.
Thank your hard work again.

**Comment by ranjian0** [comment]
Unable to duplicate: 
Using blender 2.82.7.

Create a rectangular floorplan 100mX100m
Add window on one face

RESULT:
![Imgur](https://i.imgur.com/dE4tsJO.png)

**Comment by Qomolangma888** [comment]
I test the issue on Blender 2.83.1 LTS and 2.9 Alpha, I think it is problem of Blender, I guess Building Tools is complict of Blender bundle addons. Currently, I find some workarounds to solve the problem, but they are not so good.
