### ISSUE TITLE
New Parameter: Distance between features for arrayed elements

### ISSUE THREAD

**Issue by JakubPelka** [ranjian0/building_tools#141]
Hi, 
I think it might be a good thing to add an additional parameter that could define distance between objects. 
What I mean - now if we have a wall that is 12m long, and we'd like to add 3 windows, all of them will be evenly spread (every +/- 3m). It would be nice to have the opportunity to define distance (for ex 0,5m) between objects. Then we could place them with offset tool.

And one more thing - possibility to add multiple balconies in the same way as we could add door, window or multigroups.
Will be glad if you let me know if there is a chance for adding these features.

- [x] Balcony Array
- [x] Array Spreading

**Comment by MCrafterzz** [comment]
I have accually thought about that as well (offset in miltigroup), it's a good idea!

**Comment by ranjian0** [comment]
@JakubPelka Under consideration. Not sure how this would work though!

**Comment by ranjian0** [comment]
- [ ] Balcony Array
- [ ] Array Spreading

**Comment by ranjian0** [comment]
![array_spreading](https://user-images.githubusercontent.com/13909505/106137851-5c75e000-617c-11eb-8e78-55264329bc88.gif)

Landing in 1.1 release. Already in `dev` branch
