### ISSUE TITLE
Will not start on Blender 2.83.1

### ISSUE THREAD

**Issue by cowdawg** [ranjian0/building_tools#151]
Installed from a zip file downloaded from github. Blender reports it is loaded but it does not show up anywhere on Blender.

**Comment by ranjian0** [comment]
Are you using the latest release: v1.0.2??

**Comment by cowdawg** [comment]
According to your README on GitHub it is. All I did was select code->>download zip.  Then tried to load it from preferences as a zip.. Unfortunately it is neither showing up in the checkbox list to be enabled, nor can I search for it in the plugins list and certainly it is not showing up in the N-Panel. 
![building-tool-version](https://user-images.githubusercontent.com/1289105/86937108-daa16500-c10c-11ea-9b84-aa414e4fddc6.png)

**Comment by ranjian0** [comment]
You have downloaded from Github branch which doesn't have correct layout for blender addon. Use the zip file from `releases`. Latest is [this one](https://github.com/ranjian0/building_tools/releases/download/v1.0.2/building_tools-v1.0.2.zip)
