### ISSUE TITLE
Random Building Generator

### ISSUE THREAD

**Issue by ZapUser77** [ranjian0/building_tools#164]
I'm trying to build a 1 click "random building generator" that includes interior walls as well as furniture, appliances, and other misc.
I would like to merge what you have for the exterior, with what I already have made for the interior.

https://youtu.be/FejiufiaGik 

Would this be ok?

**Comment by ranjian0** [comment]
Yes

**Comment by ZapUser77** [comment]
I have no idea how to use GitHub, but, if I get some time, I'll try and write up a script for your asset that will give ppl a "generate random" button, along with a quantity, and it'll just spawn a bunch of houses... possibly with textures.  ^_^

**Comment by ranjian0** [comment]
Your idea is closely related to issue #154. I recommend you close this issue in favour of that one but that is up to you.
Feel free to share your ideas here or over at our discord server [here](https://discord.gg/hK4UaGu).

To get started, you should have a look at the `test` folder esp `test_floors.py` to see what you would need to do to work with building tools programmatically. 

Happy hacking and Cheers.

**Comment by MCrafterzz** [comment]
> I have no idea how to use GitHub, but, if I get some time, I'll try and write up a script for your asset that will give ppl a "generate random" button, along with a quantity, and it'll just spawn a bunch of houses... possibly with textures. ^_^

That would be super cool!

**Comment by ZapUser77** [comment]
> Your idea is closely related to issue #154. 

No, they are not related.  Mine is completely random, his request is a preset.  Though, mine would require 154 as a prereq. Essentially a button that randomly assigns numbers into a preset.  ^_^

**Comment by ranjian0** [comment]
building tools now has an api that allows random generation in a more reasonable way.
see https://github.com/ranjian0/building_tools/tree/master/btools/api
