### ISSUE TITLE
Interior

### ISSUE THREAD

**Issue by Carulosu** [ranjian0/building_tools#165]
It would be great if we had the option to enable house interiors. For games where we can get inside houses, like RPGs. 
It shouldn't be really hard to implement the inside of walls, floors, doors and windows as they are basically flipped versions of the outside.
Great tool, but it feels like it's doing only half of what it could do.

**Comment by ranjian0** [comment]
To be quite frank, this would be very painful to implement in spite of it seeming simple. Building Tools has been designed with exteriors in mind, trying to accommodate what you are suggesting into the existing design will be quite unpleasant.

In any case, I am open to ideas concerning this. You are not the first user to raise this issue and I am inclined not to dismiss it.
Feel free to submit suggestions you may have.

**Comment by MCrafterzz** [comment]
Building tools have from the start been designed for exteriors, as Ian said though this could change in the future especially if someone in the community is willing to work on it but in my opinion there are still exterior stuff that needs to be added first.

**Comment by ranjian0** [comment]
I will close this as out of scope. Feel free to reopen in case of any further suggestions
