### ISSUE TITLE
I hope it can be set windows on roof.

### ISSUE THREAD

**Issue by Qomolangma888** [ranjian0/building_tools#168]
Sometimes, I will place some windows on the roof, but I select roof faces then click "Windows" button, there is no response. So, I wish you can add the function, thank you very much!

**Comment by MCrafterzz** [comment]
You can add windows to slanted faces so as long as its a tilted roof it should work.

**Comment by ranjian0** [comment]
If the roof face is not rectangular it will not work.

**Comment by MCrafterzz** [comment]
You can use the knife tool in that case to create a rectangle

**Comment by Qomolangma888** [comment]
OK, I will try it.
