### ISSUE TITLE
plugin isn't added to 2.90.1 while no problem on 2.83.4

### ISSUE THREAD

**Issue by Shaddy-ElDesouky** [ranjian0/building_tools#169]
**Describe the bug**
when I tried adding the plugin it is not added to 2.90.1 while no problem on 2.83.4

 - OS: lubuntu 20.04
 - Blender Version 2.90.1
 - Addon Version 1.0.6
 - Lenovo thinkstation S20, x5650, Gtx 1050ti, 8gb ram

**Comment by ranjian0** [comment]
Does it show an error message? If so please post here. 

I have no way of diagnosing without more information.
Screenshots would also be useful.

**Comment by Qomolangma888** [comment]
You can copy "btool\" directory to   C:\users\appdata\rooming\blender fundation\2.90.1\script\addons, then restart your blender, try it.

**Comment by BlueMints000** [comment]
Hi, I tried to install the Building tools app, but it's not taking it, I'm using Blender 2.91. It's a great app! I would love to try it and use it to make buildings faster. I'm working on Blender 2.90 but I'll be coming back to check this board out :)

**Comment by MCrafterzz** [comment]
> Hi, I tried to install the Building tools app, but it's not taking it, I'm using Blender 2.90. It's a great app! I would love to try it and use it to make buildings faster. I'm working on Blender 2.90 but I'll be coming back to check this board out :)

🤔 Don't you have any error in the system console?

**Comment by ranjian0** [comment]
I have tested the addon with blender versions 2.90.0, 2.90.1 and 2.91.0. It installs and works fine.

If you are having this problem, the issue must be with your local setup in which case we would need console logs to diagnose.
1. If you are on windows, there should be a menu item to show console.
2. If on linux, you need to open a terminal first and then run blender,

Take a screenshot on copy the text in the console.

**Comment by MCrafterzz** [comment]
> I have tested the addon with blender versions 2.90.0, 2.90.1 and 2.91.0. It installs and works fine.
> 
> If you are having this problem, the issue must be with your local setup in which case we would need console logs to diagnose.
> 
> 1. If you are on windows, there should be a menu item to show console.
> 2. If on linux, you need to open a terminal first and then run blender,
> 
> Take a screenshot or copy the text in the console and post here.

There is a debug_log.cmd file in the Blender directory on windows. Sometimes it catches things that the system log opened from within blender doesn't

**Comment by ranjian0** [comment]
> Also a few months ago a user found out that building tools had a conflict with some pipe generation addon. Do you have some pipe addon installed?

Do you have more information on this? Where did the user post? Discord??

**Comment by MCrafterzz** [comment]
> > Also a few months ago a user found out that building tools had a conflict with some pipe generation addon. Do you have some pipe addon installed?
> 
> Do you have more information on this? Where did the user post? Discord??

Yes it was in our discord, search for pipe and you'll find the discussion. Here is the addon: https://blenderartists.org/t/blender-addon-piperator-generation-of-pipe-networks-new-version-with-vertex-color-pipe-control/1186693

**Comment by ranjian0** [comment]
Closing as stale. Feel free to re-open if the issue persists
