### ISSUE TITLE
Roof direction

### ISSUE THREAD

**Issue by marcinfork** [ranjian0/building_tools#171]
I saw  on youtube  chanel there is  flip direction roof option  in  version 1.0 alpha  but i cant find this option anymore
I  use the newest version and i dont have this option 

![image](https://user-images.githubusercontent.com/58313100/99649677-ca9f7780-2a54-11eb-87b2-a19dfb2cb6c2.png)

**Comment by ranjian0** [comment]
This option is no longer available. A new gable roof implementation was introduced that would work on all polygon shapes. 
The old implementation only worked on rectangular shapes and the option to flip the roof direction was easy to implement. The new implementation supports all shapes and an option to flip direction doesn't really make sense when the roof is not rectangular.
