### ISSUE TITLE
License change needed

### ISSUE THREAD

**Issue by CONIGUERO** [ranjian0/building_tools#172]
Blender is licensed as GPLv3.

As stated on the [Blender license page](https://www.blender.org/about/license/):

> Blender’s Python API is an integral part of the software, used to define the user interface or develop tools for example. The GNU GPL license therefore requires that such scripts (if published) are being shared under a GPL compatible license. You are free to sell such scripts, but the sales then is restricted to the download service itself. Your customers will receive the script under the same license (GPL), with the same free conditions as everyone has for Blender.

Therefore all add-ons, including this one, must have the GPLv3 license.

I suggest changing the license from MIT to GPL in order to comply with Blender's license.

**Comment by MCrafterzz** [comment]
> Blender is licensed as GPLv3.
> 
> As stated on the [Blender license page](https://www.blender.org/about/license/):
> 
> > Blender’s Python API is an integral part of the software, used to define the user interface or develop tools for example. The GNU GPL license therefore requires that such scripts (if published) are being shared under a GPL compatible license. You are free to sell such scripts, but the sales then is restricted to the download service itself. Your customers will receive the script under the same license (GPL), with the same free conditions as everyone has for Blender.
> 
> Therefore all add-ons, including this one, must have the GPLv3 license.
> 
> I suggest changing the license from MIT to GPL in order to comply with Blender's license.

It does say a GPL compatible license not neccecarly GPL. MIT is compatible and is even more open that GPL so I really don't see any downsides to it. Source: https://en.m.wikipedia.org/wiki/License_compatibility#GPL_compatibility
