### ISSUE TITLE
Door "Fill Type" does not work on double doors

### ISSUE THREAD

**Issue by Sydebrix** [ranjian0/building_tools#176]
I encountered the following problem:
1. Add a door
2. Make it a double door
3. Add any kind of filling

The filling is only affecting one half of the double door. See video if not completely clear. 
https://user-images.githubusercontent.com/20229118/105062930-724c1c80-5a7b-11eb-81a5-37c3d1e4dfc5.mp4

**Comment by ranjian0** [comment]
Which version of the add-on are you using?

**Comment by Sydebrix** [comment]
v1.0.7 with blender 2.90.1

**Comment by ranjian0** [comment]
OK, I just looked into this. Small typo in door_types.py line 122. Will fix first thing tomorrow. Thanks for reporting.

**Comment by ranjian0** [comment]
Created a new release with the fix.
