### ISSUE TITLE
Update cutter vertex positions for windows and doors.

### ISSUE THREAD

**Issue by Nitecon** [ranjian0/building_tools#179]
**Is your feature request related to a problem? Please describe.**
Currently when adding windows and doors there are 4 vertices created at the outer edges, these can be optimized by merging 2 fo them to a singular and also making the extents quadrangular for better rendering.

**Describe the solution you'd like**
Update the window & door cutters to use optimized vertex placements

**Describe alternatives you've considered**
Manually merging all vertices can take a considerable amount of time.

**Additional context**
Current Window:
![WindowCurrent](https://user-images.githubusercontent.com/665977/106641239-fc54b480-6554-11eb-8942-651a6eda8f95.PNG)

Optimized Window
![WindowOptimized](https://user-images.githubusercontent.com/665977/106641271-070f4980-6555-11eb-8839-d86aec8efc1a.PNG)

Current Door
![DoorCurrent](https://user-images.githubusercontent.com/665977/106641308-0e365780-6555-11eb-8536-62396070d16a.PNG)

Optimized Door
![DoorOptimized](https://user-images.githubusercontent.com/665977/106641339-168e9280-6555-11eb-99e2-229861f31ec5.PNG)

**Comment by ranjian0** [comment]
Not sure why I had not done this already. Its a really nice request.

Hopefully, it will be easy to implement.

**Comment by luckykadam** [comment]
This was intensional to enable multigroup.

It's important to think about how multigroup would work, before make any changes.

**Comment by Nitecon** [comment]
That make sense but generally with current construction standards even multi groups would follow an inset pattern where there is a small piece of trim separating a window and a door as example, which would allow for the optimized geo still.

**Comment by luckykadam** [comment]
@Nitecon can you please share a screenshot of your idea?

Please consider complex cases: dwd, dwwd, wdw, wddw.

**Comment by ranjian0** [comment]
I have taken a look at the geometry that multi group creates. Indeed this would pose difficulties since there are no edges between adjacent multi group components.

**Comment by Nitecon** [comment]
Here are some more screenshots with the idea laid out

dwd current:
![dwd_current](https://user-images.githubusercontent.com/665977/106644973-c49c3b80-6559-11eb-8a99-4d7ec989871b.PNG)

dwd optimized example:
![dwd_optimized](https://user-images.githubusercontent.com/665977/106644992-ccf47680-6559-11eb-9297-931b1450e070.PNG)

dwwd current:
![dwwd_current](https://user-images.githubusercontent.com/665977/106645023-d67dde80-6559-11eb-9f23-826ff6e60ef7.PNG)

dwwd optimized example:
![dwwd_optimized](https://user-images.githubusercontent.com/665977/106645051-ded61980-6559-11eb-8779-be190ceb13b3.PNG)

In all of the examples it was as simple as taking the furthest corners and merging them at last (outside vertex) and for the interior pieces merging top at center.  Please note that these obviously still needs to be cleaned up more but hopefully that helps.  You guys have a fantastic product already just hoping to help with some basic ideas to improve cleanup & render ability

**Comment by ranjian0** [comment]
Also in `dwwd` the bottom mid verts between the windows can be merged.

**Comment by Nitecon** [comment]
Yep you got it

**Comment by ranjian0** [comment]
![#179_demo](https://user-images.githubusercontent.com/13909505/106863857-2a173600-66da-11eb-96d6-c5ce40ef3a1a.gif)

Was not too tricky to implement. Great suggestion!

**Comment by Nitecon** [comment]
I was out for a few well done on this looks great!
