### ISSUE TITLE
Addon Updater

### ISSUE THREAD

**Issue by BlenderDefender** [ranjian0/building_tools#186]
Hey @ranjian0,
I've been using this addon for quite a while now, and I must say, updating it is causing me trouble
because I have to keep more than 75 addons up to date. Therefore, it would be great, if you could [Implement an Updater, e.g. the one by CG Cookie](https://www.blendernation.com/2021/05/12/easily-implement-the-cg-cookie-updater-with-addon-updater/).

Greetings,
Blender Defender

**Comment by ranjian0** [comment]
Hi, thanks for the request. This will be taken into consideration in the next release.
