### ISSUE TITLE
If Blender unit scale is 0.01m, the maximum floorplan size is limited to 1x1 meter.

### ISSUE THREAD

**Issue by robotvk** [ranjian0/building_tools#189]
1. Set the units to 0.01
2. Create FloorPlan
3. Try to change Width/Length to 5 - it will stay on 1 meter.

Blender 2.93.1

**Comment by ranjian0** [comment]
I played a bit with this but I can't figure out what circumstances would lead to such a problem, which means that I can't figure out the best solution to this.

Could you elaborate more on what/how this situation would come about?

**Comment by robotvk** [comment]
I have nothing to add to my first post.
It is possible to change the width height of the floor in the blender, but not in the "create floorplan" command.
