### ISSUE TITLE
[Feature] | Adding a window to a roof

### ISSUE THREAD

**Issue by azgoodaz** [ranjian0/building_tools#192]
**Is your feature request related to a problem? Please describe.**
Yes and no. It's not a problem because I can still use the object without the window but it's just would be nice for the aesthetic look.

**Describe the solution you'd like**
This feature would give people the ability to create attics and windows to hidden floors in buildings.

**Additional context**
Currently when trying to add a window to the roof, it's not possible, as seen here.

![image](https://user-images.githubusercontent.com/10385818/132109778-94d1d46c-7791-4ea9-aee0-cae7fddd34e3.png)

**Comment by ranjian0** [comment]
Currently the tool only supports adding elements to rectangular faces. 

Normally this would be an easy feature to add using boolean but that would create unpredictable geometry which is something the tool tries to avoid. Also the tools works mostly in edit mode which doesn't lend well to boolean operations.

**Comment by ranjian0** [comment]
out of scope
