### ISSUE TITLE
Report Errors In Blender 3.0 Alpha

### ISSUE THREAD

**Issue by Qomolangma888** [ranjian0/building_tools#193]
In Blender 3.0 alpha, when I let mesh model enter into edit mode, then I press [Floor] button, Blender reports some errors, so I hope you fix the bug , Thank you so much.

**Comment by ranjian0** [comment]
Can you share a screenshot of the errors?

**Comment by ranjian0** [comment]
OK, thanks for posting the screenshot. Will look into it.
