### ISSUE TITLE
Not working Blender 3.0

### ISSUE THREAD

**Issue by Codezilluh** [ranjian0/building_tools#195]
**Describe the bug**
I get an error when trying to add floors in Blender 3.0

**To Reproduce**
In Blender 3.0, create a floorplan and attempt to add a floor.

**Screenshots**
![image](https://user-images.githubusercontent.com/84803278/143914355-ab93bd32-b3a8-45b1-a038-f403c9044741.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Blender Version: 3.0
 - Addon Version: 1.0.8

I am using 3.0 because it is much more performant on my computer. The LTS 2.93 eats most of my 16GBs of RAM.

**Comment by ranjian0** [comment]
Use master branch

**Comment by ranjian0** [comment]
Close if satisfied!

**Comment by ranjian0** [comment]
Decided to publish new release with 3.0 compatibility.

[v1.0.9 Release](https://github.com/ranjian0/building_tools/releases/tag/v1.0.9)
