### ISSUE TITLE
Using with python script 

### ISSUE THREAD

**Issue by Suprhimp** [ranjian0/building_tools#196]
Problem with using building_tools with python script

I'm very interested about this building_tools! Thanks for this super useful tools :)

But when I use with the script, I can't modify the properties. when I look the python tool tips for changing properties like width, height, count etc .. I can't find the correct way to change value with script.

I checked with the console,  when I change the count of windows , width or anything, it said only

`bpy.data.window_managers["WinMan"].(null) = (some number)`

![image](https://user-images.githubusercontent.com/73486185/144636092-857ebae3-c264-49fe-a57d-40eff6bf0e14.png)

How can I use this good tools with just python script?

**Comment by ranjian0** [comment]
I recommend you look at: 
https://github.com/ranjian0/building_tools/blob/master/btools/building/generator.py

To explain a bit, you need to use a round about way due to how properties are defined. In your example screenshot, the correct way to create a window would be to call:
```python
bpy.ops.btools.add_window()
```
unfortunately doing this would not allow you to define properties like `count`, for that you need to create a `WindowProperty`, set the values and call the window builder function with those properties.

```python
import bpy
from btools.building.window import WindowProperty
from btools.building.window.window import Window

# register window property
bpy.types.Scene.window_prop = bpy.props.PointerProperty(type=WindowProperty)

# set properties you want
bpy.context.scene.window_prop.count = 10

# generate window
Window.build(bpy.context.scene.window_prop)
```
For more guidance, please get in touch on our discord server: https://discord.gg/mD2deVPz

_**Note: While this is the solution to your problem, building tools is not currently meant to be used in this manner as no API is provided.**_

**Comment by Suprhimp** [comment]
Thanks for the nice reply :)

I register window props, but when I set the count it shows error

                  ```
  bpy.types.Scene.window_prop = bpy.props.PointerProperty(type=WindowProperty)
                    bpy.context.scene.window_prop.count = 10
```

Second line occur error, it saids "AttributeError: 'WindowProperty' object has no attribute 'array'"

and also I tried 
                     ` bpy.context.scene.window_prop.width = 5`
to change width, but it said 'WindowProperty' object has no attribute 'size_offset'

**Comment by ranjian0** [comment]
Sorry, we missed a step, the code should be: 

```python
import bpy
from btools.building.window import WindowProperty
from btools.building.window.window import Window

# register window property
bpy.utils.register_class(WindowProperty)
bpy.types.Scene.window_prop = bpy.props.PointerProperty(type=WindowProperty)

# set properties you want
bpy.context.scene.window_prop.count = 10

# generate window
Window.build(bpy.context.scene.window_prop)
```

The `register_class` function will throw an exception if the class is already registered so it may be a good idea to wrap that in a try-except. See https://github.com/ranjian0/building_tools/blob/23f4d15bcd75fce4a31d5af40622f0deaa76bf2a/btools/building/generator.py#L62

**Comment by Suprhimp** [comment]
I'll post whole code, still I have an issue

`bpy.context.scene.window_prop.count = 10`

This lines gives me error
```Traceback (most recent call last):                                                                                                                                         File "\test.py", line 49, in <module>                                                                                                                                    File "C:\Users\aswww\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\building_tools-master\btools\building\array.py",
 line 57, in count                    
self.array.count = val                                                                                                                                               
AttributeError: 'WindowProperty' object has no attribute 'array'    ```

```
import bpy
import bmesh
import numpy as np
import sys
sys.path.append("C:\\Users\\aswww\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\building_tools-master")

from btools.building.window import WindowProperty
from btools.building.window.window import Window
#objects = bpy.context.scene.objects

faceList = []
#
for obj in  bpy.data.objects:
    bpy.context.view_layer.objects.active = obj
    
    bpy.ops.object.mode_set(mode = 'EDIT')
    obj = bpy.context.edit_object
    me = obj.data
    bm = bmesh.from_edit_mesh(me)

    bm.faces.ensure_lookup_table()
    # notice in Bmesh polygons are called faces
    
    for f in bm.faces:
        s = False
        for e in f.edges:
            x1,y1 = e.verts[0].co[:2]
            x2,y2 = e.verts[1].co[:2]
            x1 = round(x1,3)
            y1 = round(y1,3)
            x2 = round(x2,3)
            y2 = round(y2,3)
            if ((x1,y1) == (7.520,9.010) and (x2,y2) == (7.39,1.67))\
                or ((x2,y2)== (7.520,9.01) and (x1,y1) == (7.39,1.67)):
                    s = True
        if s:
            zcoord = round(f.verts[0].co[2],3)
            for v in f.verts:
                if zcoord != round(v.co[2],3):
                    faceList.append(f)
                    f.select = True  # select index 4
                    
                    
                    try:
                        bpy.utils.register_class(WindowProperty)
                    except:
                        pass
                    bpy.types.Scene.window_prop = bpy.props.PointerProperty(type=WindowProperty)
                    bpy.context.scene.window_prop.count = 10
                    Window.build(bpy.context.scene.window_prop)
                    break
#                    f.select = False  # select index 4
    # Show the updates in the viewport
bmesh.update_edit_mesh(me, True)
```
This code is for selecting face that include some coordinate and put the window on that face
I success to make just default window but I can't modify any properties

If there is no API to modify properties
Can I control the Add Window Pannel than?
I'd like to find out how to change the props of the window and put in selected face on my python script :)

Sincerely

**Comment by Suprhimp** [comment]
I'll post whole code, still I have an issue

This is my code 
```
import bpy
import bmesh
import numpy as np
import sys
sys.path.append("C:\\Users\\aswww\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\building_tools-master")

from btools.building.window import WindowProperty
from btools.building.window.window import Window
#objects = bpy.context.scene.objects

faceList = []
#
for obj in  bpy.data.objects:
    bpy.context.view_layer.objects.active = obj
    
    bpy.ops.object.mode_set(mode = 'EDIT')
    obj = bpy.context.edit_object
    me = obj.data
    bm = bmesh.from_edit_mesh(me)

    bm.faces.ensure_lookup_table()
    # notice in Bmesh polygons are called faces
    
    for f in bm.faces:
        s = False
        for e in f.edges:
            x1,y1 = e.verts[0].co[:2]
            x2,y2 = e.verts[1].co[:2]
            x1 = round(x1,3)
            y1 = round(y1,3)
            x2 = round(x2,3)
            y2 = round(y2,3)
            if ((x1,y1) == (7.520,9.010) and (x2,y2) == (7.39,1.67))\
                or ((x2,y2)== (7.520,9.01) and (x1,y1) == (7.39,1.67)):
                    s = True
        if s:
            zcoord = round(f.verts[0].co[2],3)
            for v in f.verts:
                if zcoord != round(v.co[2],3):
                    faceList.append(f)
                    f.select = True  # select index 4
                    
                    
                    try:
                        bpy.utils.register_class(WindowProperty)
                    except:
                        pass
                    bpy.types.Scene.window_prop = bpy.props.PointerProperty(type=WindowProperty)
                    bpy.context.scene.window_prop.count = 10
                    Window.build(bpy.context.scene.window_prop)
                    break

    # Show the updates in the viewport
bmesh.update_edit_mesh(me, True)
```
This code is for selecting face that include some coordinate and put the window on that face
I success to make just default window but I can't modify any properties

when I run this code,  it's gives this error
```
Traceback (most recent call last):                                                                                                                                         
File "C:\Users\aswww\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in crash_handler          return func(*args, **kwargs)                                                                                                                                         TypeError: build() missing 1 required positional argument: 'prop'
```

Thanks for your kind reply :)

Sincerely

**Comment by ranjian0** [comment]
**There's is a missing argument.** 
You should be able to look up such issues by going to the file and checking what is required. 

https://github.com/ranjian0/building_tools/blob/23f4d15bcd75fce4a31d5af40622f0deaa76bf2a/btools/building/window/window.py#L15

```python
Window.build(bpy.context, bpy.context.scene.window_prop))
```

**Comment by ranjian0** [comment]
After looking at you code, I can see you are calling the Window.build in a loop which should not be necessary. 
Just select all the necessary faces in the loop and then call Window.build at the end. Windows will be created on all the selected faces.

**Comment by Suprhimp** [comment]
Thanks for your advice I'll change it

import bpy
import bmesh
import numpy as np
import sys
sys.path.append("C:\\Users\\aswww\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\building_tools-master")

from btools.building.window import WindowProperty
from btools.building.window.window import Window
from btools.building.arch import ArchProperty
from btools.building.array import ArrayProperty
from btools.building.sizeoffset import SizeOffsetProperty
#objects = bpy.context.scene.objects
try:
    bpy.utils.register_class(ArchProperty)
    bpy.utils.register_class(ArrayProperty)
    bpy.utils.register_class(SizeOffsetProperty)
    bpy.utils.register_class(WindowProperty)
except:
    pass

faceList = []
#
for obj in  bpy.data.objects:
    bpy.context.view_layer.objects.active = obj
    
    bpy.ops.object.mode_set(mode = 'EDIT')
    obj = bpy.context.edit_object
    me = obj.data
    bm = bmesh.from_edit_mesh(me)

    bm.faces.ensure_lookup_table()
    # notice in Bmesh polygons are called faces
    
    for f in bm.faces:
        s = False
        for e in f.edges:
            x1,y1 = e.verts[0].co[:2]
            x2,y2 = e.verts[1].co[:2]
            x1 = round(x1,3)
            y1 = round(y1,3)
            x2 = round(x2,3)
            y2 = round(y2,3)
            if ((x1,y1) == (7.520,9.010) and (x2,y2) == (7.39,1.67))\
                or ((x2,y2)== (7.520,9.01) and (x1,y1) == (7.39,1.67)):
                    s = True
        if s:
            zcoord = round(f.verts[0].co[2],3)
            for v in f.verts:
                if zcoord != round(v.co[2],3):
                    faceList.append(f)
                    f.select = True  # select index 4

                    break
#                    f.select = False  # select index 4
    # Show the updates in the viewport
bpy.types.Scene.window_prop = bpy.props.PointerProperty(type=WindowProperty)
bpy.context.scene.window_prop.count = 10
bpy.context.scene.window_prop.width = 2
Window.build(bpy.context,bpy.context.scene.window_prop)
bmesh.update_edit_mesh(me, True)


But still I have an issue it said
Traceback (most recent call last):                                                                                                                                        
```
 File "C:\Users\aswww\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\building_tools-master\btools\utils\util_common.py", line 81, in crash_handler          return func(*args, **kwargs)                                                                                                                                           File "C:\Users\aswww\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\building_tools-master\btools\building\window\window.py", line 22, in build             if create_window(bm, faces, prop):                                                                                                                                     File "C:\Users\aswww\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\building_tools-master\btools\building\window\window_types.py", line 63, in create_window                                                                                                                                                                        window, arch = create_window_frame(bm, face, prop)                                                                                                                     File "C:\Users\aswww\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\building_tools-master\btools\building\window\window_types.py", line 92, in create_window_frame  
    if prop.type == "CIRCULAR":                                                                                                                                          AttributeError: 'WindowProperty' object has no attribute 'type'  
```
 
I think I should use register_class(something) to solve this but I have no idea since I can't find python file about type..

**Comment by ranjian0** [comment]
full api is now implemented.
Consult https://github.com/ranjian0/building_tools/tree/master/btools/api

```python
import building_tools.btools.api as api

api.create_floorplan(api.FloorplanOptions(type=api.FloorplanType.RANDOM))
```
