### ISSUE TITLE
Features not working 

### ISSUE THREAD

**Issue by Cypmann25** [ranjian0/building_tools#197]
After installing Im only allowed to 'create a floor plan' no other features are working. 

Please see the screenshot of what is show
![Uploading image_2021-12-06_105040.png…]()
n when i try add a floor or anything else:

![image_2021-12-06_104907](https://user-images.githubusercontent.com/95613962/144815664-cf78fd51-9821-4a93-a04d-fb75d7831ffe.png)

 - Blender Version 3.0.0

**Comment by ranjian0** [comment]
Are you using the latest release?

**Comment by Ayaneko** [comment]
Yes, steam updates blender with any new releases. I am not using any kind of beta, Only the 3,0 release that was just pushed out to people. I believe my install was updated last night. For now, I have rolled my blender back to 2.93 to get the addon working again as I am using it to model buildings for a project.  But the error posted above is from the 3.0 release.

**Comment by Ayaneko** [comment]
It just dawned on me, that you likely meant the latest version of your wonderful addon. I have not updated it. I will update and let you know if I still have trouble. Sorry! :D

**Comment by rawbsterlobster** [comment]
Using latest version. Same errors

**Comment by ranjian0** [comment]
> Using latest version. Same errors

Some more info would be nice

**Comment by timyaukey** [comment]
I get the same error. Just downloaded addon from Github, and installed it in Blender 3.0. I would not be surprised if there is a breaking change in the Python scripting API going from 2.8.x/2.9.x to 3.0.x.

**Comment by ranjian0** [comment]
@timyaukey I have just downloaded blender 3.0 and installed the addon from github, everything works fine. So does the release(1.0.9) in releases.

Please provide more information on the error you have. Is your addon version 1.0.9?

**Comment by timyaukey** [comment]
I figured it out: The download link in your README.md still points to
version 1.0.8. When I downloaded 1.0.9 from the "releases" area it works
fine.

**Comment by ranjian0** [comment]
My bad, will update link in the readme

**Comment by ranjian0** [comment]
closed in 713fd62e086c4742bf967741e6cbf7e2f2f59633
