### ISSUE TITLE
Clamp value

### ISSUE THREAD

**Issue by ElMabsSarah** [ranjian0/building_tools#200]
Hello, I've been using the addon for a bit and the clamp on the depth value was bothering me so I tried to change the max value in the btool scripts to a higher value but it doesnt seem to fix the problem?

I'm wondering if there might be something I haven't taken into consideration other than changing the max valu
![Capture](https://user-images.githubusercontent.com/93084943/157432738-a1ad00ee-11f8-4ea8-b0bb-17ac41b5d664.PNG)
e

**Comment by ranjian0** [comment]
What was the problem with the old clamp value? Can you elaborate a bit more. 

Most of the values in building tools have extra clamping logic in the operators to make them work well with each other. This is mostly done to maintain reasonable proportionality for all the tools/elements. If you could point to your use case that could help a bit more in tracking down what you are struggling with.

**Comment by ranjian0** [comment]
closing stale
