### ISSUE TITLE
No way to reset properties of windoes/doors. 

### ISSUE THREAD

**Issue by kenjdavidson** [ranjian0/building_tools#211]
**Describe the bug**
When adding (for example) a window you update properties to build the appropriate window. When moving on to the next face the same properties are reused. When moving from a large face to a smaller face an exception is thrown instead of allowing properties to be reset. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a building with a long and short side 
2. Add a max number of windows to the long side 
3. Attempt to add window to shorter side. An error will occur. 
4. The only way to fix this is create a new wall/face with enough size. Add a window then lower the number. Then undo the change and apply it to the smaller side. 

**Expected behaviour**
Either the properties should reset to basic, even manually would be good. 
The window should fail but still open the properties to lower the number of windows on the shorter side. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 
 - Blender Version 3.3.1 
 - Addon Version latest 

**Additional context**
Just a way to reset props to devault would be good. Or to save presets of properties?

**Comment by ranjian0** [comment]
Not sure that blender provides a reset option for operator properties. This will either need to be done manually or perhaps reset after an operator finishes execution

**Comment by kenjdavidson** [comment]
Yes, it happens mainly on windows, but it has to do with the length of the face not being enough to accommodate the item(s).  For example, things like this cause problems:

- Adding a Double Door to a wide wall, then attempt to add a door to a smaller wall.  If the configuration of the door doesn't fit on the wall, it will error out.  
- Adding 10 windows to a long wall, then attempting to add a window to a smaller wall.  If the wall cannot accomodate all the windows it will error out.

In both cases, it's fixable by:

- Selecting or creating a large enough face
- Clearing or lowering the settings for the window/door so it would fit on the face you want
- Undoing the change
- Re-applying the new properties

**Comment by ranjian0** [comment]
This issue should be resolved in the latest release: https://github.com/ranjian0/building_tools/releases/tag/v1.0.10

The properties don't exactly reset, but clamping has been adjusted to guarantee geometry fits even in small faces. This should fix the issue across all tools. Resetting is probably not a good strategy as its hard to know the users intentions for these sort of edge cases.

Feel free to re-open the issue if you think the problem has not been addressed properly.

**Comment by kenjdavidson** [comment]
Awesome! I would agree on the reset comment. Will give it a run though on my next clubhouse.
