### ISSUE TITLE
Index out of bounds exception

### ISSUE THREAD

**Issue by kenjdavidson** [ranjian0/building_tools#213]
**Describe the bug**
I'm attempting to add a door/window to a building being designed and I'm getting the following exception:

```
building_tools updater verbose is enabled
building_tools Updater: Read in JSON settings from file
Read blend: C:\Users\User\OneDrive\Documents\OPCD Golf Course Projects\Royal Ashburn GC\clubhouse.blend
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\building_tools\btools\utils\util_common.py", line 92, in crash_handler
    return func(*args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\building_tools\btools\building\door\door_ops.py", line 49, in build
    if create_door(bm, faces, props):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\building_tools\btools\building\door\door_types.py", line 56, in create_door
    door, arch = create_door_frame(bm, face, prop)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\building_tools\btools\building\door\door_types.py", line 121, in create_door_frame
    add_faces_to_map(bm, [door_face], FaceMap.DOOR)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\building_tools\btools\building\facemap.py", line 106, in add_faces_to_map
    if obj.facemap_materials[group_index].auto_map:
IndexError: bpy_prop_collection[index]: index 10 out of range, size 8
```

As you can see in the screenshot, the door is actually created, but the properties window is not brought up.  I've tested this in both 1.0.9 and 1.0.10 (latest).

**To Reproduce**
Steps to reproduce the behaviour:
I'm unsure if using Object/Join to attach buildings is causing this problem, but it's worked in the past with other buildings I've been working on.   

**Expected behaviour**
The door should be added to the face, and the properties window should display so that the door can be modified;  As you can see in the screenshot the door is added correctly.   I've attached a share link to the blender file for which I'm working.

https://1drv.ms/u/s!AqN33biz5OLCkLxwn3Bny2rFUmi61g?e=cWB5B7

**Screenshots**
![image](https://user-images.githubusercontent.com/6210735/227727082-2b1d02ef-8170-429b-a902-bf2588f5e992.png)
![image](https://user-images.githubusercontent.com/6210735/227727282-00732a65-b1e8-47dc-a251-fa86647d4cf3.png)

**Desktop (please complete the following information):**
- Windows
- 3.4
- 2.83 also

> Attempted this in both blender versions.

**Comment by ranjian0** [comment]
Hmm, will look into it this week.

**Comment by ranjian0** [comment]
> I'm unsure if using Object/Join to attach buildings is causing this problem, but it's worked in the past with other buildings I've been working on.

Looks like object join destroys the layout of the material facemaps and that causes the error. It will be quite tricky to resolve this without user intervention but I will try.

**Comment by kenjdavidson** [comment]
That's what I assumed. I wouldn't worry (closing the issue). This library is absolutely fantastic and has helped me learn blender (although I'm still pretty bad). I appreciate the support.
