### ISSUE TITLE
Window's Frame smashes in once depths changed. & Windows are sometimes classified as frame

### ISSUE THREAD

**Issue by RobloxS-Distributor** [ranjian0/building_tools#215]
**Window frames smashes into the wall once depth's changed**
![image](https://github.com/ranjian0/building_tools/assets/109883172/a6d9bc4e-423f-4faf-8bc9-90f53b929578)

As you can see, top frame smashes into the wall, I have no idea how to fix that.

It could be solved by making a window, editing its depth, copy its format, and remove the old one and paste the new window.
This isn't just window frames, but anything that has a frame.

**Windows categorized as frame**
It's completely annoying how windows classify as frames, it should hopefully be fixed.

![image](https://github.com/ranjian0/building_tools/assets/109883172/159a28c6-3221-4a99-b64c-dc904a968a58)

**Comment by ranjian0** [comment]
Thanks for posting the issue, will look into it this week. Cheers.

**Comment by RobloxS-Distributor** [comment]
> Thanks for posting the issue, will look into it this week. Cheers.

# **Depth Issues (More In-Sight)** 

Thank you, all of the bugs stated were caused by depth being changed.

* The frame of the doors & windows bug's out once the depth is change even by a millimeter.
* For the windows being classified as frame, it is also caused by depth being changed.
* There's also another bug where you cannot modify the offset of the door going up and down, only left and right.

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

On a positive note, aside from the mentioned bugs, I would like to express my gratitude for developing this plugin!

As a suggestion for the future, consider creating a premium version of this with additional features, potentially as a paid plugin. This could be a great way for you to benefit from your hard work.

Once again, thank you for the plugin you have saved a lot of people, have a fantastic day!

**Comment by ranjian0** [comment]
> * There's also another bug where you cannot modify the offset of the door going up and down, only left and right.

This is not really a bug, doors are always anchored at the bottom so offsetting up and down does not make sense. Best you can do is adjust the height.
