### ISSUE TITLE
is it possible to add support to blender 4.0+?

### ISSUE THREAD

**Issue by leanoon** [ranjian0/building_tools#216]
hi, i like your amazing tools ! thank you for your great work!
but seems it can't work under blender 4.0
so is it possible to add support to blender 4.0+ ?

best wishes!!

**Comment by ranjian0** [comment]
Thanks for posting the issue, I will look into it ASAP.

**Comment by leanoon** [comment]
WOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOW！

**Comment by ranjian0** [comment]
It seems that there was a critical change in the python API. They removed the `face_maps` feature with was the core component of the Material Workflow

API Change Doc: https://wiki.blender.org/wiki/Reference/Release_Notes/4.0/Python_API
Commit: https://projects.blender.org/blender/blender/commit/46cf09327001331c77bcd54ceab73404a1733172#diff-87e0b417a3f9d71206a75a00e011bb1b93b3539c

This is not something that can easily be made backwards compatible in the addon which means once we move to the new attributes system that replaces `face_maps`, the addon will no longer work older versions of blender i.e < 4.0

**Comment by leanoon** [comment]
wow！ your action fast than light! 
so good news!!!

**Comment by ranjian0** [comment]
Blender 4.0 support added in https://github.com/ranjian0/building_tools/releases/tag/v1.0.11
