### ISSUE TITLE
Impossible to activate the plugin in my configuration osx

### ISSUE THREAD

**Issue by messagescdl** [ranjian0/building_tools#219]
It seems not compatible with my configuration ?
->  impossible to 'activate' the plugin after installation (zip downloaded, install through menu blender/edit/preferences/addon), the following error message appends.
Comment :  
This file is empty : "/Users/mbpcedric/Library/Application Support/Blender/4.0/scripts/addons/building_tools\_init_py",

Configuration :
- Blender Version 4.0.2 (4.0.2 2023-12-05)
- Addon Version : v1.0.11
- Mac Osx Sonoma / Apple M3max

<img width="482" alt="Capture d’écran 2023-12-27 à 21 14 32" src="https://github.com/ranjian0/building_tools/assets/155012991/d6a7497d-e532-4079-af37-a4effac36d65">
<img width="747" alt="Capture d’écran 2023-12-27 à 21 15 12" src="https://github.com/ranjian0/building_tools/assets/155012991/00f7d0e0-3205-4f9b-88f4-d6c7625e6d82">

**Comment by messagescdl** [comment]
Hello, 
I'm interested in this tool but but didn't worked for me, bug info above. 
I don't know if it's normal with my configuration, then I'm publishing behavior with my system. 
Thanks in advance for any advice.

**Comment by ranjian0** [comment]
Thanks for the report. I'm looking into it.
