### ISSUE TITLE
Create Wiki

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tools#23]
Add detailed wiki to help users with:
- [x] Installation.
- [x] Creating Floorplan.
- [x] Creating Floors.
- [x] Creating Windows.
- [x] Creating Doors.
- [x] Creating Multigroup
- [x] Creating Roofs.
- [x] Creating Stairs.
- [x] Creating Balconies.
- [x] Add Fill tool
- [x] Development.

Not Implemented Yet.
- [x] Creating roads
- [x] Using the curved array tool

**Comment by LinkinJX** [comment]
I can help creating the wiki if you want, adding step by step gifs if needed

**Comment by ranjian0** [comment]
> I can help creating the wiki if you want, adding step by step gifs if needed

That would be much appreciated. I have been postponing this issue since the start of this year.

**Comment by LinkinJX** [comment]
Just give me some guidelines and I'll start as soon as posible ✍️

**Comment by ranjian0** [comment]
Do you know how to use `git`?

**Comment by LinkinJX** [comment]
I know what it is but I don't really know how to use it. And you're right, I'm completely new here.

Thank you. I'll probably start editing the Wiki tomorrow.

**Comment by LinkinJX** [comment]
I've started editing the Usage page, I'll start adding images soon.
Is the format ok so far?

**Comment by MCrafterzz** [comment]
> I've started editing the Usage page, I'll start adding images soon.
> Is the format ok so far?

Looks good to me

**Comment by ranjian0** [comment]
> I've started editing the Usage page, I'll start adding images soon.
> Is the format ok so far?

The format is OK. I was actually thinking we should use different pages for each module. Having all the modules described in one page is overkill e.g usage wiki for `doors` can have a page `usage_door`. 

I think this will be a lot cleaner to navigate and faster too. Also, the `table of contents` will be much more useful then, already the Usage page is quite long due to images/gifs and I have to scroll about 4 times from the bottom to access the `ToC`.

It may also be useful to highlight some tips e.g `Users can generate their own floorplans`. Such information is not obvious to users. This could include properties that change the default behaviour e.g when creating random floorplan, the `Random Extension Amount` changes default behaviour and should be highlighted in some way.

Perhaps before you add more info on the other modules like `Door` we can use `Floorplan` and `Floors` wiki to test the best way to reveal all this information. 

Example Formatting

    Module Title
    - Creation with default properties
        (GIF)
    - Properties
       description of the properties with optional images
    - Tips
       useful to know information when using the module

**Comment by LinkinJX** [comment]
I think you're right, I'll start editing it soon.
My doubt is what format should I give to the main Usage page.

**Comment by MCrafterzz** [comment]
> I think you're right, I'll start editing it soon.
> My doubt is what format should I give to the main Usage page.

Maybe it could be a list with link that redirect to the respective pages

**Comment by ranjian0** [comment]
For the main usage page, we can include general guidelines when using modules.
 
A good example of stuff to put here is common properties like `Array Property` and `Size & Offset Property` which are shared by multiple modules.

Also, we can put tips on having the correct context e.g `Selection` and `Mode`. Some of this change per module and it may be useful to make users aware in one common place.

**Comment by MCrafterzz** [comment]
@LinkinJX btw you should join our discord server!

**Comment by ranjian0** [comment]
@LinkinJX Let me take care of the main usage page. You can focus on individual modules. I will try to get this done this week.

**Comment by ranjian0** [comment]
Wiki is mostly done. I Will keep updating this as new features get added
