### ISSUE TITLE
Backwards Compatibility for 2.79

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tools#28]
It seems I overreacted by discontinuing support for 2.79. There was so much hype for 2.80, it did not occur to me that some users would want to remain in 2.79.

Fortunately, I have discovered myself that there are perfectly valid reasons why some users are in 2.79 still, and I feel obligated to provide support for them. The addon thread on Blender Artists has quite a few.

The 2.79 addon will be maintained in a separate branch `stable-v2.79`. Although there are plenty of resources on how keep blender python code backwards compatible, I prefer to avoid all that mess and keep the code separate.

The original 2.80 port issue #2, is a nice guide for this.

**Comment by HUMPHREY-75** [comment]
Please where and how can I download 2.79 version. Please send link to coyprokonsultld@gmail.com

Meanwhile thank you in advance.

Humphrey

**Comment by ranjian0** [comment]
Currently, a 2.79 version does not exist, hence why this issue exists. Sorry for the inconvenience. It may be a while before I have time to work on this.

**Comment by HUMPHREY-75** [comment]
Oh! Thanks for letting me know so fast

**Comment by ranjian0** [comment]
Due to limited development time and little interest in this, will close.

**Comment by HUMPHREY-75** [comment]
Thanks for letting me know about this. I have upgraded to blender 2.83, and
add-on is doing just fine.
