### ISSUE TITLE
Custom Models

### ISSUE THREAD

**Issue by rektuiemforameme** [ranjian0/building_tools#95]
Hi, can I use my own models with this? For example, if I wanted to use a window I made instead of the ones provided?

**Comment by ranjian0** [comment]
This is not currently possible. Not with the help of the addon. 
Perhaps you should label this as feature request i.e `enhancement` label. 
Be sure to describe how you may want this to work.

**Comment by rektuiemforameme** [comment]
I don't think I can add a label. 
    Basically, I was thinking you could replace the models of the modular components with custom models that follow the same modular format. So in this screenshot, the feature would let the user use the custom window that's selected as one of the options in the dialogue for adding windows.
![Annotation 2020-05-25 170803](https://user-images.githubusercontent.com/47416827/82843184-5a030e00-9eaa-11ea-89e5-53174a05283a.png)

**Comment by ranjian0** [comment]
If the custom models are fixed size and not expected to change, this may work. Otherwise, users may be required to parameterize the custom models. 
As mentioned in issue #98, such custom models can't possibly have the customization of the current tools.

@rektuiemforameme, for instance, you would not be able to change the thickness of the frames with the help of the addon.

**Comment by ranjian0** [comment]
Off the top of my head, a possible way to implement this would be:
1. Have an object selection property that allows the user to choose the custom object they would like to add.
2. The addon should calculate the size/bounds of the custom object.
3. The user would then select the faces where the object should be added.
4. Then click the operator button, say, `Add Custom` which would cut holes on the selected faces and fit the custom object.

_Possible issues may be disconnected/duplicate geometry_

**Comment by ranjian0** [comment]
Adding this to 1.1 milestone for further consideration!

**Comment by MCrafterzz** [comment]
Would be nice if the default option was procedural but you can choose to place a model instead if you have some advanced special window. In this case the mesh would be copied and placed at the selected positions. Parameters aren't needed as you won't want to change thickness for example as you already have created the model exactly like you wanted.

**Comment by ranjian0** [comment]
> Would be nice if the default option was procedural but you can choose to place a model instead if you have some advanced special window. In this case the mesh would be copied and placed at the selected positions. Parameters aren't needed as you won't want to change thickness for example as you already have created the model exactly like you wanted.

Some generic parameters like `count` used for arraying may be useful. 

I think that this should be its own tool and not an extra option in existing ones like window and the like. It can be called for instance `Placement Tool` and be used for both destructive details like cutting holes to add windows/doors and non destructively e.g to add extra objects on-top of roof. The `dormers` in issue #40 is a good example of this.

**Comment by ranjian0** [comment]
**Progress report.**

![cutom-model-2020-09-28-225840](https://user-images.githubusercontent.com/13909505/94480166-92ab4f00-01de-11eb-9679-c508daed0ac2.gif)

Still, quite a few kinks to work out but already geometry and materials are transferred nicely from the custom mesh to the target mesh. Currently, the tool works by cutting holes on the target mesh and placing the custom model. Placement without cutting holes will be added.

Some constraints on the custom model also exist. e.g
- The model has to be front-facing (Y+ Axis)
- Depending on the model, resizing by the tool could cause disproportional features.

Ideas and Suggestions welcome!
